name: "Mealie Planner"
description: "A simple kitchen planner for Mealie. Browse your recipe library and plan meals for the week"
url: "https://github.com/hawkinslabdev/mealie-planner"
version: "0.5.0"
slug: "mealie_planner"
arch:
  - aarch64
  - amd64
startup: application
init: false
ingress: true
ingress_port: 3000

panel_title: "Mealie Planner"
panel_icon: "mdi:silverware-variant"
panel_admin: false

apparmor: true
hassio_role: default
host_network: false
host_pid: false
host_ipc: false
full_access: false
docker_api: false

options:
  mealie_url: ""
  api_token: ""
schema:
  mealie_url: "str?"
  api_token: "str?"
