name: "Mealie Planner"
description: "A simple kitchen planner for Mealie. Browse your recipe library and plan meals for the week"
url: "https://github.com/hawkinslabdev/mealie-planner"
version: "0.2.0"
slug: "mealie_planner"
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 3000
panel_icon: "mdi:silverware-variant"
options:
  mealie_url: ""
  api_token: ""
schema:
  mealie_url: "str?"
  api_token: "str?"
